apiVersion: v2
name: isovalent-openshift-console-plugin
description: OpenShift Console plugin for Isovalent / Cilium (CiliumNetworkPolicy, CiliumClusterwideNetworkPolicy) with a deep link to Isovalent Hubble Timescape.
type: application
version: 0.1.3
appVersion: v0.0.5
home: https://github.com/christianh814/isovalent-openshift-console-plugin
sources:
  - https://github.com/christianh814/isovalent-openshift-console-plugin
maintainers:
  - name: christianh814
    url: https://github.com/christianh814
annotations:
  org.opencontainers.image.source: https://github.com/christianh814/isovalent-openshift-console-plugin
  org.opencontainers.image.description: OpenShift Console plugin for Isovalent / Cilium
  org.opencontainers.image.licenses: Apache-2.0
